### ISSUE TITLE
Attempting to use a disposed semaphore

### ISSUE THREAD

**Issue by alex-sherman** [Steffen-M/dotnet-ResourceAccessManager#2]
When one task acquires a lock twice and then releases while a second task is waiting on the lock, once it releases the lock an exception will be thrown because the origin task has disposed the semaphore. 

**Edit:** There appears to also be a race condition sometimes where both task1 and task2 can acquire the lock simultaneously.

Example:

```c#
static void Main(string[] args)
{
    // Task2 throws an exception when releasing the lock
    var t1 = task1();
    var t2 = task2();
    Task.WhenAll(t1, t2).GetAwaiter().GetResult();
    Console.ReadLine();
}
static async Task task1()
{
    var lock1 = await ResourceAccessManager.Default.LockAsync("other");
    using (lock1)
    using (lock1)
    {
        Console.WriteLine("Lock acquired");
        await Task.Delay(100);
    }
    Console.WriteLine("Lock released");
}
static async Task task2()
{
    await Task.Delay(50);
    using (await ResourceAccessManager.Default.LockAsync("other"))
    {
        Console.WriteLine("Lock acquired");
    }
    Console.WriteLine("Lock released");
}
```

**Comment by Steffen-M** [comment]
Thanks for testing!
The issue is not a race condition, rather than calling Dispose twice on the resource handle (that's what happens "using" it twice).
I've improved handling such a situation in the code.
